import { expect, test } from '@playwright/test';
import {readFile} from 'node:fs/promises';

test('weekly review keeps its draft and saves one focus note offline',async({page,context})=>{
  await page.setViewportSize({width:1440,height:900});
  await page.goto('/');await page.getByRole('button',{name:'Use Nook without an account'}).click();
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();
  await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);
  await page.getByRole('button',{name:'Open weekly review',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Clear the Inbox',exact:true})).toBeVisible();
  await page.locator('.weekly-review-grid').screenshot({path:'artifacts/visual/web-review.png'});
  await page.getByRole('button',{name:'Review',exact:true}).click();
  await page.getByRole('button',{name:'Check',exact:true}).click();
  await page.getByRole('button',{name:'Choose',exact:true}).click();
  await page.getByRole('textbox',{name:'Next focus',exact:true}).fill('Weekly offline focus');
  await page.reload();await page.getByRole('button',{name:'Open weekly review',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Next focus',exact:true})).toHaveValue('Weekly offline focus');
  await page.getByRole('button',{name:'Save focus',exact:true}).click();
  await page.getByRole('button',{name:'Edit note',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Note body',exact:true})).toHaveValue('Weekly offline focus');
  await page.getByRole('button',{name:'Today',exact:true}).click();await page.getByRole('button',{name:'Open weekly review',exact:true}).click();
  await page.getByRole('textbox',{name:'Next focus',exact:true}).fill('Weekly focus revised');
  await page.getByRole('button',{name:'Save focus',exact:true}).click();
  await page.getByRole('button',{name:'Edit note',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Note body',exact:true})).toHaveValue('Weekly focus revised');
  await page.getByRole('button',{name:'Search',exact:true}).click();await page.getByRole('textbox',{name:'Search your Nook'}).fill('Weekly focus');
  await expect(page.getByRole('button',{name:/note Weekly focus ·/})).toHaveCount(1);
});

test('a dated daily note edits, links and reopens without duplicate creation offline',async({page,context})=>{
  await page.goto('/');await page.getByRole('button',{name:'Use Nook without an account'}).click();
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();
  await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);
  await page.getByRole('button',{name:'Projects',exact:true}).click();
  await page.getByRole('textbox',{name:'New project title'}).fill('Garden focus');
  await page.getByRole('button',{name:'+ Add project'}).click();
  await page.getByRole('button',{name:'Calendar',exact:true}).click();
  await page.getByLabel('Daily agenda',{exact:true}).fill('2026-09-30');
  await page.getByRole('button',{name:'Open daily note',exact:true}).click();
  await page.getByRole('textbox',{name:'Note body',exact:true}).fill('## Wins\n\nDaily offline journal');
  await page.getByRole('combobox',{name:'Link related item',exact:true}).selectOption({label:'Garden focus'});
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await page.reload();await page.getByRole('button',{name:'Calendar',exact:true}).click();
  await page.getByLabel('Daily agenda',{exact:true}).fill('2026-09-30');
  await page.getByRole('button',{name:'Open daily note',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Note body',exact:true})).toHaveValue('## Wins\n\nDaily offline journal');
  await expect(page.getByRole('button',{name:'Garden focus',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Search',exact:true}).click();
  await page.getByRole('textbox',{name:'Search your Nook'}).fill('Daily offline journal');
  await expect(page.getByRole('button',{name:'dailyNote Daily note · 2026-09-30',exact:true})).toHaveCount(1);
});

test('saving an unsaved project draft preserves its archive state offline',async({page,context})=>{
  await page.goto('/');await page.getByRole('button',{name:'Use Nook without an account'}).click();
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();
  await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);
  await page.getByRole('button',{name:'Projects',exact:true}).click();
  await page.getByRole('textbox',{name:'New project title'}).fill('Archived garden');
  await page.getByRole('button',{name:'+ Add project'}).click();
  await page.getByRole('textbox',{name:'Outcome',exact:true}).fill('Keep this unsaved outcome');
  await page.getByRole('button',{name:'Archive',exact:true}).last().click();
  await expect(page.getByRole('button',{name:'Restore',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await page.reload();await page.getByRole('button',{name:'Archive',exact:true}).click();
  await page.getByRole('button',{name:/Archived garden/}).click();await page.getByText('Project details',{exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Outcome',exact:true})).toHaveValue('Keep this unsaved outcome');
  await expect(page.getByRole('button',{name:'Restore',exact:true})).toBeVisible();
});

test('Markdown selection formatting, note links, backlinks and original attachments work offline',async({page,context})=>{
  await page.goto('/'); await page.getByRole('button',{name:'Use Nook without an account'}).click();
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;}); await page.reload();
  await page.waitForFunction(()=>!!navigator.serviceWorker.controller); await context.setOffline(true);
  async function note(body:string,title:string) {
    await page.getByRole('button',{name:'Quick capture',exact:true}).click();
    await page.getByRole('textbox',{name:'Thought',exact:true}).fill(body);
    await page.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();
    await page.getByRole('button',{name:'Inbox',exact:true}).click();
    await page.getByRole('button',{name:'Note',exact:true}).click();
    await page.getByRole('textbox',{name:'Title',exact:true}).fill(title);
    await page.getByRole('button',{name:'Save',exact:true}).click();
    await expect(page.getByRole('status')).toContainText('Saved locally');
  }
  await note('A destination','Garden'); await note('hello world','Editor proof');
  await page.getByRole('button',{name:'Edit note',exact:true}).click();
  const body=page.getByRole('textbox',{name:'Note body',exact:true});
  await body.evaluate((element:HTMLTextAreaElement)=>{element.focus();element.setSelectionRange(6,11);});
  await page.getByRole('button',{name:'Bold',exact:true}).click();
  await expect(body).toHaveValue('hello **world**');
  await body.fill('hello **world**\n[[Garden]]\n`[[Garden]]`\n<script>alert(1)</script>');
  await page.getByLabel('Add attachment',{exact:true}).setInputFiles({name:'proof.txt',mimeType:'text/plain',buffer:Buffer.from('original offline bytes')});
  await expect(page.getByRole('button',{name:'proof.txt',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Preview',exact:true}).click();
  await expect(page.locator('.markdown strong')).toHaveText('world');
  await expect(page.locator('.markdown script')).toHaveCount(0);
  await expect(page.locator('.markdown code')).toHaveText('[[Garden]]');
  await page.getByRole('button',{name:'Garden',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Title',exact:true})).toHaveValue('Garden');
  await page.getByRole('textbox',{name:'Title',exact:true}).fill('Renamed garden');
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await page.getByRole('button',{name:'Editor proof Linked note',exact:true}).click();
  await page.getByRole('button',{name:'Edit note',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Note body',exact:true})).toHaveValue(/hello \*\*world\*\*/);
  await expect(page.getByRole('button',{name:'proof.txt',exact:true})).toBeVisible();
  await page.reload(); await page.getByRole('button',{name:'Search',exact:true}).click();
  await page.getByRole('textbox',{name:'Search your Nook'}).fill('Editor proof');
  await page.getByRole('button',{name:'note Editor proof',exact:true}).click();
  await expect(page.getByRole('button',{name:'proof.txt',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Garden',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Title',exact:true})).toHaveValue('Renamed garden');
  await page.getByRole('button',{name:'Editor proof Linked note',exact:true}).click();
  const [download] = await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'proof.txt',exact:true}).click()]);
  expect((await readFile((await download.path())!)).toString()).toBe('original offline bytes');
});

test('repeat configuration keeps unsaved edits and creates the next task offline', async ({page, context}) => {
  await page.goto('/');
  await page.getByRole('button', {name: 'Use Nook without an account'}).click();
  await page.evaluate(async () => {await navigator.serviceWorker.ready;});
  await page.reload();
  await page.waitForFunction(() => !!navigator.serviceWorker.controller);
  await context.setOffline(true);
  await page.getByRole('button', {name: 'Quick capture', exact: true}).click();
  await page.getByRole('textbox', {name: 'Thought', exact: true}).fill('Plant care');
  await page.getByRole('button', {name: 'Save', exact: true}).click();
  await page.getByRole('button', {name: 'Inbox', exact: true}).click();
  await page.getByRole('button', {name: 'Task', exact: true}).click();
  await page.getByLabel('Do date', {exact: true}).fill('2026-09-30');
  await page.getByLabel('Deadline', {exact: true}).fill('2026-10-02');
  await page.getByRole('combobox', {name: 'Frequency', exact: true}).selectOption('weekly');
  await page.getByLabel('First scheduled date', {exact: true}).fill('2026-09-30');
  await page.getByRole('button', {name: 'Save repeat schedule'}).click();
  await expect(page.getByRole('status')).toContainText('Repeat schedule saved');
  await expect(page.getByLabel('Do date', {exact: true})).toHaveValue('2026-09-30');
  await page.getByLabel('Completed', {exact: true}).check();
  await page.getByRole('button', {name: 'Save', exact: true}).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await page.reload();
  await page.getByRole('button', {name: 'Search', exact: true}).click();
  await page.getByRole('textbox', {name: 'Search your Nook'}).fill('Plant care');
  await expect(page.getByRole('button', {name: 'task Plant care', exact: true})).toHaveCount(2);
  await page.getByRole('button', {name: 'task Plant care', exact: true}).last().click();
  await expect(page.getByLabel('Completed', {exact: true})).not.toBeChecked();
  await expect(page.getByLabel('Do date', {exact: true})).toHaveValue('2026-10-07');
  await expect(page.getByLabel('Deadline', {exact: true})).toHaveValue('2026-10-09');
});

test('capture, clarify, edit, organize, complete, search, delete and reopen offline', async ({page,context}) => {
  await page.goto('/');
  await page.getByRole('button',{name:'Use Nook without an account'}).click();
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;});
  await page.reload();
  await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
  await context.setOffline(true);
  await page.getByRole('button',{name:'Quick capture',exact:true}).click();
  await page.getByRole('textbox',{name:'Thought',exact:true}).fill('Offline proof');
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Saved to Inbox');
  await page.getByRole('button',{name:'Inbox',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Offline proof',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Task',exact:true}).click();
  await page.getByRole('textbox',{name:'Title',exact:true}).fill('Offline proof edited');
  const today = await page.evaluate(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;});
  await page.getByLabel('Do date',{exact:true}).fill(today);
  await page.getByLabel('Deadline',{exact:true}).fill('2030-12-31');
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await page.getByRole('button',{name:'Today',exact:true}).click();
  await page.getByRole('checkbox',{name:'Complete Offline proof edited'}).click();
  await expect(page.getByRole('checkbox',{name:'Complete Offline proof edited'})).toHaveCount(0);
  await page.getByRole('button',{name:'Search',exact:true}).click();
  await page.getByRole('textbox',{name:'Search your Nook'}).fill('proof');
  await page.getByRole('button',{name:'task Offline proof edited'}).click();
  await expect(page.getByLabel('Completed',{exact:true})).toBeChecked();
  await expect(page.getByLabel('Deadline',{exact:true})).toHaveValue('2030-12-31');
  await page.getByRole('button',{name:'Archive',exact:true}).last().click();
  await page.getByRole('button',{name:'Archive',exact:true}).first().click();
  await page.getByRole('button',{name:'Restore',exact:true}).click();
  await page.getByRole('button',{name:'Search',exact:true}).click();
  await page.getByRole('textbox',{name:'Search your Nook'}).fill('proof');
  await page.getByRole('button',{name:'task Offline proof edited'}).click();
  await page.getByRole('button',{name:'Delete',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Deleted locally');
  await page.reload();
  await page.getByRole('button',{name:'Search',exact:true}).click();
  await page.getByRole('textbox',{name:'Search your Nook'}).fill('proof');
  await expect(page.getByRole('button',{name:'task Offline proof edited'})).toHaveCount(0);
  await page.getByRole('button',{name:'Quick capture',exact:true}).click();
  await page.getByRole('textbox',{name:'Thought',exact:true}).fill('Persist this offline note');
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await page.getByRole('button',{name:'Inbox',exact:true}).click();
  await page.getByRole('button',{name:'Note',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Organized locally');
  await page.reload();
  await page.getByRole('button',{name:'Search',exact:true}).click();
  await page.getByRole('textbox',{name:'Search your Nook'}).fill('persist');
  await expect(page.getByRole('button',{name:'note Persist this offline note'})).toBeVisible();
});

test('keyboard capture is accessible and opens without a required type or folder',async({page})=>{
  await page.goto('/');await page.getByRole('button',{name:'Use Nook without an account'}).click();
  await page.keyboard.press('Control+j');
  await expect(page.getByRole('textbox',{name:'Thought',exact:true})).toBeFocused();
  await page.keyboard.type('A keyboard thought');await page.keyboard.press('Control+Enter');
  await expect(page.getByRole('status')).toContainText('Saved to Inbox');
});
