import {useState} from 'react';
import type {Entity} from '../../../../packages/schemas/src';
import {useRepository,localDate} from './runtime';
import {saveWeeklyFocus,weekStart} from '../data/weekly-review';
type Draft={step:number;focus:string;reviewed:string[];inboxStart?:number};
const headings=['Clear the Inbox','Review active projects','Check Areas',"Choose next week’s focus"];
export function WeeklyReview({captures,projects,areas,open,inbox,act}: {captures:Entity[];projects:Entity[];areas:Entity[];open:(r:Entity)=>void;inbox:()=>void;act:(work:()=>Promise<unknown>,message?:string)=>Promise<void>}) { const repository=useRepository();
  const key=`nook-review:${repository.accountId}:${weekStart(localDate())}`;
  const [draft,setDraft]=useState<Draft>(()=>{try{const saved=JSON.parse(localStorage.getItem(key)??'null');if(saved && Number.isInteger(saved.step) && saved.step>=0 && saved.step<4 && typeof saved.focus==='string' && Array.isArray(saved.reviewed)&&saved.reviewed.every((id:unknown)=>typeof id==='string'))return saved;}catch{/* An invalid device-local draft can be safely replaced. */}return {step:0,focus:'',reviewed:[],inboxStart:captures.length};});
  const [saving,setSaving]=useState(false);
  const inboxStart=Math.max(Number.isFinite(draft.inboxStart)?draft.inboxStart!:captures.length,captures.length);
  const processed=Math.max(0,inboxStart-captures.length);
  function update(change:Partial<Draft>) {const next={...draft,...change};localStorage.setItem(key,JSON.stringify(next));setDraft(next);}
  function review(record:Entity) {update({reviewed:[...new Set([...draft.reviewed,record.id])]});open(record);}
  return <div className="weekly-review-grid"><div className="review-steps">{headings.map((heading,index)=><section className="panel review-step" key={heading}><div className="review-number"><img alt="" src={`/figma/5-183-imgEllipse${index+5}.svg`}/><span>{index+1}</span></div><div className="review-step-content"><h3>{heading}</h3><p className="small muted">{index===0?`${captures.length} waiting`:index===1?`${projects.length} active · What’s the next visible action?`:index===2?'Anything quietly slipping?':'One thing is enough'}</p>{draft.step===index&&index===1&&projects.map(record=><button className="linked-record" key={record.id} onClick={()=>review(record)}>{'title' in record.data?record.data.title:''}{draft.reviewed.includes(record.id)?' · Reviewed':''}</button>)}{draft.step===index&&index===2&&areas.map(record=><button className="linked-record" key={record.id} onClick={()=>review(record)}>{'title' in record.data?record.data.title:''}</button>)}{index===3&&draft.step===3&&<label>Next focus<textarea value={draft.focus} onChange={e=>update({focus:e.target.value})} placeholder="What matters for the week ahead?"/></label>}</div><button className="primary" aria-expanded={draft.step===index} onClick={()=>index===0?(update({inboxStart}),inbox()):update({step:index})}>{['Process','Review','Check','Choose'][index]}</button></section>)}</div><aside><section className="panel elevated"><span className="pill indigo">THIS WEEK</span><h2>Progress, not perfection.</h2><p className="muted small">You need one you return to.</p><hr/><p className="small">Inbox processed · {inboxStart?`${processed} / ${inboxStart}`:'Nothing waiting'}</p><progress className="inbox-review-progress" aria-label="Inbox processed" max={Math.max(inboxStart,1)} value={processed}/><p className="small">Projects reviewed · {projects.filter(r=>draft.reviewed.includes(r.id)).length} / {projects.length}</p><progress aria-label="Projects reviewed" max={Math.max(projects.length,1)} value={projects.filter(r=>draft.reviewed.includes(r.id)).length}/><button className="primary" onClick={()=>update({step:3})}>Finish review</button>{draft.step===3&&<button disabled={!draft.focus.trim()||saving} onClick={()=>{setSaving(true);void act(async()=>{open(await saveWeeklyFocus(repository,localDate(),draft.focus));},'Focus saved locally').finally(()=>setSaving(false));}}>Save focus</button>}</section><section className="panel review-tip"><span className="pill yellow">NO STREAKS</span><h3>Missing a review doesn’t reset anything.</h3><p className="muted small">Come back when the system starts feeling noisy.</p></section></aside></div>;
}
